services:
  postgres:
    image: postgres:15
    container_name: laravel_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: laravel_db
      POSTGRES_USER: laravel_user
      POSTGRES_PASSWORD: secret
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./backup.sql:/docker-entrypoint-initdb.d/backup.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U laravel_user -d laravel_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
        context: .
        args:
            - FLUX_USERNAME=${FLUX_EMAIL} # O la variable que contenga tu email de Flux
            - FLUX_PASSWORD=${FLUX_KEY}
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
      - storage_data:/var/www/html/storage
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DB_CONNECTION: pgsql
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      FRESH_DB: ${FRESH_DB:-false}
      FLUX_EMAIL: ${FLUX_EMAIL}
      FLUX_KEY: ${FLUX_KEY}

volumes:
  pgdata:
  storage_data:
